require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CharacterEntriesController do

  # This should return the minimal set of attributes required to create a valid
  # CharacterEntry. As you add validations to CharacterEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CharacterEntriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all character_entries as @character_entries" do
      character_entry = CharacterEntry.create! valid_attributes
      get :index, {}, valid_session
      assigns(:character_entries).should eq([character_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested character_entry as @character_entry" do
      character_entry = CharacterEntry.create! valid_attributes
      get :show, {:id => character_entry.to_param}, valid_session
      assigns(:character_entry).should eq(character_entry)
    end
  end

  describe "GET new" do
    it "assigns a new character_entry as @character_entry" do
      get :new, {}, valid_session
      assigns(:character_entry).should be_a_new(CharacterEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested character_entry as @character_entry" do
      character_entry = CharacterEntry.create! valid_attributes
      get :edit, {:id => character_entry.to_param}, valid_session
      assigns(:character_entry).should eq(character_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CharacterEntry" do
        expect {
          post :create, {:character_entry => valid_attributes}, valid_session
        }.to change(CharacterEntry, :count).by(1)
      end

      it "assigns a newly created character_entry as @character_entry" do
        post :create, {:character_entry => valid_attributes}, valid_session
        assigns(:character_entry).should be_a(CharacterEntry)
        assigns(:character_entry).should be_persisted
      end

      it "redirects to the created character_entry" do
        post :create, {:character_entry => valid_attributes}, valid_session
        response.should redirect_to(CharacterEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved character_entry as @character_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        CharacterEntry.any_instance.stub(:save).and_return(false)
        post :create, {:character_entry => {  }}, valid_session
        assigns(:character_entry).should be_a_new(CharacterEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CharacterEntry.any_instance.stub(:save).and_return(false)
        post :create, {:character_entry => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested character_entry" do
        character_entry = CharacterEntry.create! valid_attributes
        # Assuming there are no other character_entries in the database, this
        # specifies that the CharacterEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CharacterEntry.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => character_entry.to_param, :character_entry => { "these" => "params" }}, valid_session
      end

      it "assigns the requested character_entry as @character_entry" do
        character_entry = CharacterEntry.create! valid_attributes
        put :update, {:id => character_entry.to_param, :character_entry => valid_attributes}, valid_session
        assigns(:character_entry).should eq(character_entry)
      end

      it "redirects to the character_entry" do
        character_entry = CharacterEntry.create! valid_attributes
        put :update, {:id => character_entry.to_param, :character_entry => valid_attributes}, valid_session
        response.should redirect_to(character_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the character_entry as @character_entry" do
        character_entry = CharacterEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CharacterEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => character_entry.to_param, :character_entry => {  }}, valid_session
        assigns(:character_entry).should eq(character_entry)
      end

      it "re-renders the 'edit' template" do
        character_entry = CharacterEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CharacterEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => character_entry.to_param, :character_entry => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested character_entry" do
      character_entry = CharacterEntry.create! valid_attributes
      expect {
        delete :destroy, {:id => character_entry.to_param}, valid_session
      }.to change(CharacterEntry, :count).by(-1)
    end

    it "redirects to the character_entries list" do
      character_entry = CharacterEntry.create! valid_attributes
      delete :destroy, {:id => character_entry.to_param}, valid_session
      response.should redirect_to(character_entries_url)
    end
  end

end
